# Exercícios de NumPy

 Agora que já estudamos o **NumPy**, é hora de praticar!

 Começaremos com tarefas simples e, em seguida, avançaremos para questões mais desafiadoras.

#### Importe o NumPy como np

#### Crie um array de 10 zeros

#### Crie um array de 10 uns

#### Crie um array de 10 cincos

#### Crie um array com os inteiros de 10 até 50

#### Crie um array com todos os inteiros pares de 10 até 50

#### Crie uma matriz 3x3 com valores de 0 até 8

#### Crie uma matriz identidade 3x3

#### Gere um número aleatório entre 0 e 1 usando NumPy

#### Gere um array com 25 números aleatórios de uma distribuição normal padrão

#### Crie a seguinte matriz:
```
[[ 0,  1,  2,  3,  4],

 [ 5,  6,  7,  8,  9],

 [10, 11, 12, 13, 14],

 [15, 16, 17, 18, 19],

 [20, 21, 22, 23, 24]]

```

#### Crie um array de 20 pontos igualmente espaçados entre 0 e 1

## Indexação e Seleção em NumPy

Agora, você receberá algumas matrizes e deverá **replicar as saídas esperadas**.

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

Escreva código que produza a seguinte saída:

```
[[12 13 14 15]

 [17 18 19 20]

 [22 23 24 25]]
```

Escreva código que produza a seguinte saída:

```
20
```

Escreva código que produza a seguinte saída:

```
[[ 2]

 [ 7]

 [12]]
```

Escreva código que produza a seguinte saída:

```
[21 22 23 24 25]
```

Escreva código que produza a seguinte saída:

```
[[16 17 18 19 20]

 [21 22 23 24 25]]
```

### Agora faça o seguinte:

#### Obtenha a soma de todos os valores de `mat`

#### Obtenha o desvio padrão dos valores de `mat`

#### Obtenha a soma de cada coluna de `mat`

## Exercícios extras (desafio)

Para praticar ainda mais, tente resolver:
1. Crie uma matriz 10x10 com valores de 0 a 99.
2. Inverta a ordem dos elementos em um array (ex: `[1,2,3] → [3,2,1]`).
3. Crie um array 5x5 com valores aleatórios entre 0 e 1 e encontre o valor **máximo e mínimo**.
4. Gere uma matriz diagonal 4x4 com os valores `[10,20,30,40]`.
5. Crie uma matriz 6x6 com números inteiros aleatórios entre 1 e 100 e calcule a média de cada linha.
6. Gere uma matriz 5x5 com números da distribuição normal e conte quantos valores são **maiores que 1**.
7. Crie um array de 100 valores espaçados logaritmicamente entre `10^1` e `10^3`.
8. Multiplique duas matrizes 3x3 (produto matricial).
9. Crie uma função que receba um array NumPy e retorne a quantidade de valores únicos.
10. Desafie-se: Crie o tabuleiro de xadrez (8x8) usando apenas 0s e 1s.

### Situação-Problema 1: Monitoramento de Temperaturas em Biomas
**Contexto:**

Você é um pesquisador do IBAMA que está monitorando as temperaturas médias semanais em três biomas brasileiros: Amazônia, Cerrado e Caatinga. Os dados foram coletados ao longo de 4 semanas, organizados como uma matriz:

In [ ]:
# Linhas: Semanas (1 a 4)
# Colunas: Biomas [Amazônia, Cerrado, Caatinga]
import numpy as np

temperaturas = np.array([
    [30.5, 25.2, 28.1],
    [31.2, 26.0, 27.8],
    [29.8, 24.5, 28.6],
    [30.0, 25.7, 29.0]
])

**Desafios:**
1. Calcule a temperatura média mensal de cada bioma.
1. Descubra em qual semana cada bioma teve sua maior temperatura.
1. Verifique em quais semanas a temperatura da Amazônia foi maior que 30°C.
1. Calcule a variação de temperatura (máximo - mínimo) de cada bioma ao longo do mês.

In [ ]:
# Sua solução aqui

### Situação-Problema 2: Qualidade da Água em Estações de Monitoramento

**Contexto:**

Você está analisando os níveis de **oxigênio dissolvido (OD)** em mg/L em 5 rios diferentes, monitorados em 3 estações ao longo do ano. Os dados de OD foram armazenados em uma matriz tridimensional:

In [ ]:
# Eixos: (Estações, Dias, Rios)
# Dias: 10 primeiros dias do mês
np.random.seed(42)
od = np.random.uniform(4.5, 9.0, size=(3, 10, 5))  # OD varia entre 4.5 e 9.0 mg/L

Desafios:
1. Calcule o **valor médio de OD** em cada rio, por estação.
1. Encontre **o dia com menor nível de OD em cada rio**, por estação.
1. Verifique **quais rios** apresentaram OD abaixo de **5 mg/L**, considerado nível de risco.
1. Use `np.where()` para identificar **os índices [estação, dia, rio]** onde isso aconteceu.
1. Gere um array com os dados **normalizados** entre 0 e 1.

In [ ]:
# Sua solução aqui

## Conclusão

Hoje exploramos o **NumPy**. Aprendemos como utilizá-lo para lidar com arrays e realizar operações numéricas de forma eficiente. Na próxima aula, vamos iniciar com **Pandas**, uma biblioteca para análise e manipulação de dados em tabelas.

---

## Sugestão de Leitura Complementar

- [Documentação oficial do Python](https://docs.python.org/3/)
- [Python Tutor - visualize seu código passo a passo](https://pythontutor.com/)
- [NumPy](https://numpy.org/doc/stable/index.html)
- [NumPy Tutorial](https://www.w3schools.com/python/numpy/default.asp)
- [Pandas](https://pandas.pydata.org/)
- [Matplotlib](https://matplotlib.org/)

---

### Salve este notebook!  
Lembre-se de salvar seu progresso (Ctrl+S ou `File > Save Notebook`) para poder retomar depois.